export const PLANPILOT_HELP_TEXT = [
  "Planpilot - Plan/Step/Goal auto-continue workflow.",
  "",
  "Model:",
  "- plan -> step -> goal",
  "- step.executor: ai | human",
  "- status rolls up: goals -> steps -> plan",
  "",
  "Rules (important):",
  "- Prefer assigning steps to ai. Use human steps only for actions that require human approval/credentials",
  "  or elevated permissions / destructive operations (e.g. GitHub web UI, sudo, deleting data/files).",
  "- One step = one executor. Do NOT mix ai/human work within the same step.",
  "  If a person must do something, create a separate human step.",
  "- Keep statuses up to date. Mark goals/steps done as soon as they are completed so roll-up and auto-continue stay correct.",
  "- `step wait` is ONLY for asynchronous, non-blocking external work that is already in progress",
  "  (build/test/job/CI/network/remote service).",
  "  If you can run something now, do it instead of waiting.",
  "  Do NOT use `step wait` to wait for human action.",
  "- Keep comments short and decision-focused.",
  "",
  "Status propagation:",
  "- Step with goals: done iff ALL goals are done; else todo.",
  "- Plan with steps: done iff ALL steps are done; else todo.",
  "- Step with 0 goals: manual status (`step update` / `step done`).",
  "- Plan with 0 steps: manual status (`plan update` / `plan done`).",
  "- When a plan becomes done, it is removed from active plan.",
  "",
  "Auto-continue:",
  "- When the session is idle and an active plan exists:",
  "  - if next pending step.executor is ai: Planpilot auto-sends the next step + goals.",
  "  - if next pending step.executor is human: no auto-continue.",
  "- Pause while waiting on external systems: `step wait`.",
  "- Stop auto-continue:",
  "  - `plan deactivate`, OR",
  "  - insert a human step BEFORE the next pending ai step (so the next executor becomes human).",
  "",
  "Invocation:",
  "- argv is tokenized: [section, subcommand, ...args]",
  "- section: help | plan | step | goal",
  "",
  "Commands:",
  "- help",
  "",
  "Plan:",
  "- plan add-tree <title> <content> --step <content> [--executor ai|human] [--goal <content>]... [--step ...]...",
  "- plan list [--scope project|all] [--status todo|done|all] [--limit N] [--page N] [--order id|title|created|updated] [--desc]",
  "- plan count [--scope project|all] [--status todo|done|all]",
  "- plan search --search <term> [--search <term> ...] [--search-mode any|all] [--search-field plan|title|content|comment|steps|goals|all] [--match-case] [--scope project|all] [--status todo|done|all] [--limit N] [--page N] [--order id|title|created|updated] [--desc]",
  "- plan show <id>",
  "- plan export <id> <path>",
  "- plan comment <id> <comment> [<id> <comment> ...]",
  "- plan update <id> [--title <title>] [--content <content>] [--status todo|done] [--comment <comment>]",
  "- plan done <id>",
  "- plan remove <id>",
  "- plan activate <id> [--force]",
  "- plan show-active",
  "- plan deactivate",
  "",
  "Step:",
  "- step add <plan_id> <content...> [--executor ai|human] [--at <pos>]",
  "- step add-tree <plan_id> <content> [--executor ai|human] [--goal <content> ...]",
  "- step list <plan_id> [--status todo|done|all] [--executor ai|human] [--limit N] [--page N]",
  "- step count <plan_id> [--status todo|done|all] [--executor ai|human]",
  "- step show <id>",
  "- step show-next",
  "- step wait <id> --delay <ms> [--reason <text>]",
  "- step wait <id> --clear",
  "- step comment <id> <comment> [<id> <comment> ...]",
  "- step update <id> [--content <content>] [--status todo|done] [--executor ai|human] [--comment <comment>]",
  "- step done <id> [--all-goals]",
  "- step move <id> --to <pos>",
  "- step remove <id...>",
  "",
  "Goal:",
  "- goal add <step_id> <content...>",
  "- goal list <step_id> [--status todo|done|all] [--limit N] [--page N]",
  "- goal count <step_id> [--status todo|done|all]",
  "- goal show <id>",
  "- goal comment <id> <comment> [<id> <comment> ...]",
  "- goal update <id> [--content <content>] [--status todo|done] [--comment <comment>]",
  "- goal done <id...>",
  "- goal remove <id...>",
].join("\n")

export const PLANPILOT_TOOL_DESCRIPTION = [
  "Planpilot planner for auto-continue plan workflows.",
  "For multi-step and complex tasks, use Planpilot to structure work into plans/steps/goals.",
  "Run `planpilot help` for full usage + rules.",
].join("\n")

export const PLANPILOT_SYSTEM_INJECTION =
  "If the task is multi-step or complex, must use the `planpilot` plan tool. For full usage + rules, run: planpilot help."

export function formatPlanpilotAutoContinueMessage(input: {
  timestamp: string
  stepDetail: string
  triggerDetail?: string
}): string {
  const detail = (input.stepDetail ?? "").trimEnd()
  const trigger = (input.triggerDetail ?? "").trim()
  return [
    `Planpilot @ ${input.timestamp}`,
    "This message was automatically sent by the Planpilot tool because the next pending step executor is ai.",
    ...(trigger ? [`Trigger context: ${trigger}`] : []),
    "For full usage + rules, run: planpilot help",
    "Next step details:",
    detail,
  ].join("\n")
}
